version: '3.8'

services:
  vle-portal:
    build: .
    container_name: vle_review_portal
    ports:
      - "8500:8501"
    env_file:
      - .env
    volumes:
      # Persist local app.log logs on the host system
      - ./app.log:/app/app.log
    restart: unless-stopped
